# Generated by Django 3.1 on 2021-07-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0004_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('finance', 'Finance'), ('engineering', 'Engineering'), ('engineering', 'Sales/Marketing')], max_length=200),
        ),
    ]
