# Generated by Django 3.1 on 2021-07-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0006_auto_20210717_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='closing_Date',
            field=models.DateField(),
        ),
    ]
